In [55]:
import pandas as pd
from matplotlib import pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression 
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import r2_score,mean_squared_error 
from sklearn.preprocessing import StandardScaler

In [56]:
data=pd.read_csv(r"final_data.csv")

In [57]:
data

,Age,Gender,Device_Type,Daily_Phone_Hours,Social_Media_Hours,Work_Productivity_Score,Sleep_Hours,Stress_Level,App_Usage_Count,Caffeine_Intake_Cups,Weekend_Screen_Time_Hours,Occupation_Business Owner,Occupation_Freelancer,Occupation_Professional,Occupation_Student
0,58,1,0,1.3,6.7,6,8.8,4,42,1,8.7,0,0,1,0
1,25,1,0,1.2,1.5,5,6.4,1,51,3,5.1,0,0,1,0
2,19,1,1,5.3,5.7,5,9.0,4,14,5,6.3,0,0,0,1
3,35,0,1,5.8,2.5,2,5.7,3,36,6,12.8,1,0,0,0
4,33,1,0,7.9,1.3,4,5.7,3,37,5,9.9,0,1,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
49995,44,1,0,5.9,5.4,5,6.6,1,11,5,3.0,1,0,0,0
49996,42,2,0,2.9,7.4,9,6.3,2,20,4,6.2,1,0,0,0
49997,27,0,1,1.4,2.5,4,6.7,9,39,4,5.1,0,1,0,0
49998,41,0,1,8.9,3.0,6,5.5,2,51,0,9.2,1,0,0,0
49999,46,2,0,8.8,2.8,3,5.4,1,54,5,6.9,0,1,0,0

Target = Stress_Level

In [58]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 50000 entries, 0 to 49999
Data columns (total 15 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   Age                        50000 non-null  int64
 1   Gender                     50000 non-null  int64
 2   Device_Type                50000 non-null  int64
 3   Daily_Phone_Hours          50000 non-null  float64
 4   Social_Media_Hours         50000 non-null  float64
 5   Work_Productivity_Score    50000 non-null  int64
 6   Sleep_Hours                50000 non-null  float64
 7   Stress_Level               50000 non-null  int64
 8   App_Usage_Count            50000 non-null  int64
 9   Caffeine_Intake_Cups       50000 non-null  int64
 10  Weekend_Screen_Time_Hours  50000 non-null  float64
 11  Occupation_Business Owner  50000 non-null  int64
 12  Occupation_Freelancer      50000 non-null  int64
 13  Occupation_Professional    50000 non-null  int64
 14  Occupation_Student         50000 non-null  int64
dtypes: float64(4), int64(11)
memory usage: 5.7 MB

In [59]:
X=data.drop(["Stress_Level"],axis=1)

In [60]:
X.shape

(50000, 14)

In [61]:
y=data["Stress_Level"]

In [62]:
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2)

In [63]:
X_test.shape

(10000, 14)

In [64]:
y_train.shape

(40000,)

In [65]:
y_test.shape

(10000,)

In [66]:
model_LR=LinearRegression().fit(X_train,y_train)
y_pred_LR=model_LR.predict(X_test)
LinearRegression_r2=r2_score(y_test,y_pred_LR) 
print(LinearRegression_r2)

-0.00028297287774115

In [67]:
from sklearn.svm import SVR
model_SVR=SVR().fit(X_train,y_train)
y_pred_SVR=model_SVR.predict(X_test)
SVR_r2=r2_score(y_test,y_pred_SVR) 
print(SVR_r2)

-0.005561613940320731

In [ ]:
from sklearn.ensemble import RandomForestRegressor
model_RFR=RandomForestRegressor().fit(X_train,y_train)
y_pred_RFR=model_RFR.predict(X_test)
model_RFR_r2=r2_score(y_test,y_pred_RFR) 
print(model_RFR_r2)

-0.02585608223926239

In [69]:
from sklearn.tree import DecisionTreeRegressor
model_DTR=DecisionTreeRegressor().fit(X_train,y_train)
y_pred_DTR=model_DTR.predict(X_test)
model_DTR_r2=r2_score(y_test,y_pred_DTR) 
print(model_DTR_r2)

-1.0177245431071738

In [70]:
X_test.head()

,Age,Gender,Device_Type,Daily_Phone_Hours,Social_Media_Hours,Work_Productivity_Score,Sleep_Hours,App_Usage_Count,Caffeine_Intake_Cups,Weekend_Screen_Time_Hours,Occupation_Business Owner,Occupation_Freelancer,Occupation_Professional,Occupation_Student
19389,34,0,1,4.1,2.1,5,8.0,42,2,8.1,0,0,1,0
48031,27,0,0,5.7,3.7,2,6.0,47,0,7.4,0,1,0,0
8621,35,0,1,4.8,7.2,9,6.4,33,0,4.7,0,0,0,1
29660,32,0,0,1.9,0.7,4,6.0,16,0,13.2,0,0,0,1
11528,25,0,1,8.8,6.1,7,8.2,58,1,2.3,1,0,0,0

In [71]:
y_test

19389     2
48031     5
8621      2
29660    10
11528     4
         ..
22692     5
702       3
12038     5
957       6
45025     2
Name: Stress_Level, Length: 10000, dtype: int64

In [72]:
data[data["Stress_Level"]==5]

,Age,Gender,Device_Type,Daily_Phone_Hours,Social_Media_Hours,Work_Productivity_Score,Sleep_Hours,Stress_Level,App_Usage_Count,Caffeine_Intake_Cups,Weekend_Screen_Time_Hours,Occupation_Business Owner,Occupation_Freelancer,Occupation_Professional,Occupation_Student
15,31,1,0,11.6,5.5,9,8.9,5,29,0,7.9,1,0,0,0
17,50,0,0,10.8,5.7,8,4.5,5,57,0,5.3,0,0,0,1
19,19,2,0,3.9,4.2,1,6.0,5,45,2,11.8,0,0,1,0
35,31,1,0,7.1,2.0,9,8.4,5,58,0,6.1,0,1,0,0
37,24,1,1,3.9,6.4,6,7.9,5,57,1,5.1,0,1,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
49918,40,0,1,11.6,3.5,8,8.6,5,20,6,11.9,0,0,1,0
49926,59,2,1,2.9,1.9,2,6.7,5,39,6,3.9,1,0,0,0
49939,40,1,0,2.8,6.4,6,6.3,5,53,5,10.3,0,0,1,0
49956,42,0,0,9.5,2.4,10,8.0,5,15,1,3.7,0,0,1,0
49957,25,0,1,4.1,1.6,3,7.5,5,54,6,10.0,0,1,0,0